library(shinytest2)

test_that("{shinytest2} recording: app", {
  app <- AppDriver$new(variant = platform_variant(), name = "app", height = 959,
                       width = 1619)
  app$set_inputs(species = 1.61)
  app$click("goButton1")
  app$expect_screenshot()
  app$set_inputs(plotTabs = "Size")
  app$expect_screenshot()
  app$set_inputs(plotTabs = "Guilds")
  app$expect_screenshot()
  app$set_inputs(plotTabs = "Diet")
  app$set_inputs(diet_species_select = "Gurnard")
  app$expect_screenshot()
  app$set_inputs(species_name_select = "Herring")
  app$set_inputs(plotTabs = "Species")
  app$click("goButton1")
  app$expect_screenshot()
  app$set_inputs(year = 9)
  app$set_inputs(mortnsp_tab = "Mortality")
  app$set_window_size(width = 1619, height = 959)
  app$set_inputs(mortspecies = 0.143)
  app$click("goButton3")
  app$expect_screenshot()
  app$set_inputs(species_order_mort = "Size")
  app$expect_screenshot()
  app$set_inputs(triplotToggleMort = TRUE)
  app$set_inputs(triplotToggleMort = FALSE)
  app$set_inputs(mortyear = 11)
  app$click("goButton3")
  app$set_inputs(plotTabs_mort = "Guilds")
  app$expect_screenshot()
  app$set_inputs(bigtabpanel = "Fishery Strategy")
  app$set_window_size(width = 1619, height = 959)
  app$set_inputs(effort_Industrial = 0.5)
  app$set_inputs(effort_Pelagic = 0.65)
  app$click("goButton2")
  app$expect_screenshot()
  app$set_inputs(fishy_plots = "Yield")
  app$expect_screenshot()
  app$set_inputs(fishy_plots = "Size")
  app$expect_screenshot()
  app$set_inputs(fishy_plots = "Guild")
  app$expect_screenshot()
  app$set_inputs(fishy_plots = "Spectra")
  app$expect_screenshot()
  app$set_inputs(fishy_plots = "Diet")
  app$set_inputs(fish_name_select = "Gurnard")
  app$expect_screenshot()
  app$set_inputs(fishy_plots = "Nutrition")
  app$expect_screenshot()
  app$set_inputs(effort2_Beam = 0.8)
  app$click("goButton22")
  app$expect_screenshot()
})
